apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-prod
resources:
- ../../base
- ingress.yaml
images:
- name: ghcr.io/phanthienquoc/media-generation
  newTag: 7be165ab693a8ac7b2fb4ee43a1224d39a59a2ed
