apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-prod
resources:
- ../../base
- ingress.yaml
images:
- name: ghcr.io/phanthienquoc/media-generation
  newTag: afcd9221d06542f352e7750a852b1a727bf0b08e
