apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-prod
resources:
- ../../base
- ingress.yaml
images:
- name: ghcr.io/phanthienquoc/media-generation
  newTag: 6b56961e09e38d181e920a8e3671f1666396ee33
