apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../platform/cert-manager
- ../../platform/microfe
- ../../apps/stockdividend/overlays/prod
- ../../apps/tce-dashboard/overlays/prod
- ../../apps/media-generation/overlays/prod
# reconcile trigger: current TCE production release - image guard fixed
