apiVersion: v1
kind: ResourceQuota
metadata:
  name: stock-budget
  namespace: stock-prod
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 6Gi
    pods: "10"
    jobs.batch: "10"
