apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tce-mrcute-tls
  namespace: tce-prod
spec:
  secretName: tce-mrcute-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - tce.mrcute.space
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stock-mrcute-tls
  namespace: stock-prod
spec:
  secretName: stock-mrcute-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - mrcute.space
  - www.mrcute.space
  - admin.mrcute.space
  - api.mrcute.space
